name: user_repository
description: A Demo project.
version: 0.0.1
publish_to: 'none'

environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # equatable: ^2.0.5
  firebase_auth: ^4.16.2
  cloud_firestore: ^4.4.2
  # firebase_storage: ^11.6.0
  rxdart: ^0.27.7
  # path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true